"""Add cover_url column to the books table

Revision ID: 828616846668
Revises: 
Create Date: 2025-01-13 11:53:44.660976

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '828616846668'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('authors', schema=None) as batch_op:
        batch_op.drop_column('date_of_death')

    with op.batch_alter_table('books', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cover_url', sa.String(length=500), nullable=True))
        batch_op.add_column(sa.Column('rating', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('books', schema=None) as batch_op:
        batch_op.drop_column('rating')
        batch_op.drop_column('cover_url')

    with op.batch_alter_table('authors', schema=None) as batch_op:
        batch_op.add_column(sa.Column('date_of_death', sa.DATE(), nullable=False))

    # ### end Alembic commands ###
